// <auto-generated />
using CineFile.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CineFile.Migrations
{
    [DbContext(typeof(CineFileContext))]
    [Migration("20230814204542_MovieGenre")]
    partial class MovieGenre
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CineFile.Models.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MovieId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            Genre = "Woolly Mammoth",
                            Title = "Matilda"
                        },
                        new
                        {
                            MovieId = 2,
                            Genre = "Dinosaur",
                            Title = "Rexie"
                        },
                        new
                        {
                            MovieId = 3,
                            Genre = "Dinosaur",
                            Title = "Matilda"
                        },
                        new
                        {
                            MovieId = 4,
                            Genre = "Shark",
                            Title = "Pip"
                        },
                        new
                        {
                            MovieId = 5,
                            Genre = "Dinosaur",
                            Title = "Bartholomew"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
